services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file: .env.postgres
    ports:
      - '1234:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: